spring.application.name=bootheat
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/

# DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/bootheat
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# MVC
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Multipart (?? ??? ??)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Static Resource (??? ?? ?? ?? ??)
# ???? ?? ???? ?? "uploads/" ??? ?? ???? ??
spring.web.resources.static-locations=classpath:/static/,file:/home/ubuntu/bootheat/uploads/
#spring.mvc.static-path-pattern=/uploads/**
#spring.web.resources.static-locations=classpath:/static/,file:/home/ubuntu/uploads/
